name: Trigger auto deployment for devops-app-jamil

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/devops-app-jamil-AutoDeployTrigger-76f4ce5e-ed1e-4036-9304-3d82a2de5399.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEVOPSAPPJAMIL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEVOPSAPPJAMIL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEVOPSAPPJAMIL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.DEVOPSAPPJAMIL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEVOPSAPPJAMIL_REGISTRY_PASSWORD }}
          containerAppName: devops-app-jamil
          resourceGroup: devops-rg-jamil
          imageToBuild: my0wndocker/devops-app-jamil:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


